version: '3.9'

services:
  node:
    container_name: node_8969dfee
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: sh -c 'npm install && npm run start'
    ports:
      - '3001:3001'
    networks:
      net_8969dfee:
        ipv4_address: 10.5.0.5
    volumes:
      - ./backend:/usr/app

  react:
    container_name: react_8969dfee
    build:
      context: ./frontend
      dockerfile: Dockerfile
    entrypoint: sh -c 'npm install && npm run start'
    ports:
      - '3000:3000'
    networks:
      net_8969dfee:
        ipv4_address: 10.5.0.6
    volumes:
      - ./frontend:/usr/app

  mysql:
    container_name: mysql_8969dfee
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /tmp/8969dfee_mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database_8969dfee
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      net_8969dfee:
        ipv4_address: 10.5.0.7
    restart: always
    ports:
      - '3306:3306'

networks:
  net_8969dfee:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
